### ISSUE TITLE
US1: As an unregistered user, I want to be able to register as a user with my chosen credentials to access the content accessible for regstred users

### ISSUE THREAD

**Issue by bauerDOTuzh** [sopra-fs22-group-23/server#1]
## Acceptance Criteria
- [x] After successful registration, the user is automatically logged in and the personal overview  is shown
- [x] After successful registration, the user’s credentials are saved in the database
- [x] Upon failure, an error is displayed, and the user is redirected to the register or login screen. The username has to be unique.
- [x] Logged-in users can log out and log back into their registered profile.

## Development task list
- [x] sopra-fs22-group-23/client#2
- [x] sopra-fs22-group-23/client#1
- [x] sopra-fs22-group-23/server#7
- [x] sopra-fs22-group-23/server#26
- [x] sopra-fs22-group-23/server#29
