### ISSUE TITLE
US5: As a registered user I want to be able to edit the profile picture given in my profile in order to provide an up-to-date impression of myself and control the publication of my personal data.

### ISSUE THREAD

**Issue by bauerDOTuzh** [sopra-fs22-group-23/server#10]
## Acceptance Criteria

- [ ] Edit button in user’s personal overview page
- [ ] Optional data points that can be changed is the profile picture
- [ ] If no profile picture is given, the user’s initials are displayed as a profile picture instead
- [ ] A registered user can only change their own profile and not the profiles of other users.
- [ ] After changing and saving the data, the user is redirected to his/her overview and the new/changed data is displayed

## Task List
- [x] sopra-fs22-group-23/client#11
- [x] sopra-fs22-group-23/client#12
- [x] sopra-fs22-group-23/server#38
- [x] sopra-fs22-group-23/server#39
