### ISSUE TITLE
US6: As a registered user I want to create an event and set the starting parameters in order to make use of the web app’s planning features (planning sessions).

### ISSUE THREAD

**Issue by bauerDOTuzh** [sopra-fs22-group-23/server#11]
## Acceptance Criteria

- [x] A “create event” button must be accessible from either a user’s personal overview or the search page for events.
- [x] With the starting parameters the creator also specifies the ToDos for successful planning of the event (e.g. “put together a banger playlist”).
- [x] Once the starting parameters are saved, the user must be given Creator status for that specific event.
- [x] The event is added to the creation section in the user's personal overview.

## Task List
- [x] sopra-fs22-group-23/client#13
- [x] sopra-fs22-group-23/client#14
- [x] sopra-fs22-group-23/server#40
- [x] sopra-fs22-group-23/server#41
