### ISSUE TITLE
US7: An event Creator wants to invite Guests and Collaborators to his/her event in order to advertise the event and share the planning responsibility with Collaborators. 

### ISSUE THREAD

**Issue by bauerDOTuzh** [sopra-fs22-group-23/server#12]
## Acceptance Criteria

- [ ] The Creator is the only one able to invite registered users by searching/filtering a list of usernames. Clicking an “invite” button next to a username invites the user to the event.
- [ ] Once invited, the Creator’s event is added to an invitee’s personal overview (invitations section).
- [ ] The chosen Collaborators see the event in their personal overview (collaboration section).
- [ ] Guests and Collaborators must be notified about the invitation. When looking at the personal overview, new events in the section are highlighted until the page is refreshed.

## Task List
- [x] sopra-fs22-group-23/client#15
- [x] sopra-fs22-group-23/client#16
- [x] sopra-fs22-group-23/server#42
- [x] sopra-fs22-group-23/server#43
- [x] #109
