### ISSUE TITLE
US8: As a user or site visitor, I want to enroll in events to collaborate in event planning phases and be an active member.

### ISSUE THREAD

**Issue by bauerDOTuzh** [sopra-fs22-group-23/server#13]
## Acceptance Criteria

- [ ] Users or simple site visitors should be able to easily enroll in an event by clicking a button
- [ ] Registered users are simply assigned according to the event, visible in their profile.
- [ ] Registered users have instant access to the enrolled events in their personal overview

## Task List
- [x] sopra-fs22-group-23/client#17
- [x] sopra-fs22-group-23/client#18
- [x] #44
