### ISSUE TITLE
US9:  As an unregistered site visitor, I want to be sent a mail, to inform me of this event planning invitation

### ISSUE THREAD

**Issue by bauerDOTuzh** [sopra-fs22-group-23/server#14]
## Acceptance Criteria

- [ ] Unregistered site visitors should be sent details by mail
- [ ] The sent email should contain a link to the public event as well as a tokenized registration link auto-assigning the initial event to their user upon registration

## Task List
- [x] sopra-fs22-group-23/server#46
- [x] sopra-fs22-group-23/server#45
