### ISSUE TITLE
US10: As a registered user that was invited to a private event, I want to gain access to the event’s private overview in order to inform myself about the event’s parameters

### ISSUE THREAD

**Issue by bauerDOTuzh** [sopra-fs22-group-23/server#15]
## Aceptance Criteria

- [ ] Private events can only be found (in search events) and checked out (event overview) by invited users
- [ ] Unregistered users can be invited via email. This invitation mail should contain a save link to the private event overview.
- [ ] In the private event overview, invited users have the option to accept or decline the invitation. If they accept, their profile picture is made visible in a “participants” section in the overview.

## Taks List
- [x] sopra-fs22-group-23/client#21
- [x] sopra-fs22-group-23/client#22
- [ ] sopra-fs22-group-23/client#23
- [x] sopra-fs22-group-23/client#24
- [x] #110
