### ISSUE TITLE
US11: As an event Creator, I want to adjust parameters (such as title, date, time, location, ...), in order to gain flexibility in the planning process and keep invitees of his/her event up to date about changes

### ISSUE THREAD

**Issue by bauerDOTuzh** [sopra-fs22-group-23/server#16]
## Acceptance Criteria

- [ ] By clicking an “edit event” button on the event overview screen the Creator is redirected to a direct manipulation interface, where the events parameters (see above) can be altered.
- [ ] After changing parameters, clicking a “save changes” button saves changes
- [ ] Only the Creator of an event should be able to change its parameters.
- [ ] Invitees are notified about changes. They see a pop-up bar on their screen (the page they’re on doesn’t matter) with the event's name. Clicking the name redirects them to the now changed event overview.

## Task List
- [x] sopra-fs22-group-23/client#25
- [x] sopra-fs22-group-23/client#26
- [x] sopra-fs22-group-23/server#48
- [x] #47
