### ISSUE TITLE
US12: As a user, I should be able to search through available events by way of filtering for predefined parameters or searching in relation to event details on the main dashboard, to increase usability.

### ISSUE THREAD

**Issue by bauerDOTuzh** [sopra-fs22-group-23/server#17]
## Acceptance Criteria

- [ ] Filters should allow users to restrict displayed events along with the parameters: area/location, type of event, date, and other event details such as the number of attendants.
- [ ] The search function should match the search with publicly available event data including description, organization, location, date, and the type of event.
- [ ] These two methods for searching events from the set should be enhanced with user-friendly interfaces e.g. date selector for date search.

## Task LIst
- [x] sopra-fs22-group-23/client#28
- [x] sopra-fs22-group-23/client#29
- [x] #49
- [x] #89
- [x] #108
