### ISSUE TITLE
US13: As an event creator or promoting user I want to share events via a link to increase flexibility

### ISSUE THREAD

**Issue by bauerDOTuzh** [sopra-fs22-group-23/server#18]
## Acceptance Criteria

- [ ]  For public events, the event should be accessible by the public and for private events, only the allowed users have access to it.
- [ ] Attendants can be added/invited to private events. For private events, only they shall have access to the non-public event details.
- [ ] If an uninvited user accesses a private event, it should show an alert or message describing missing access.
- [ ] Public events can simply be shared by copying the URL.

## Task List
- [ ] sopra-fs22-group-23/client#33
- [ ] sopra-fs22-group-23/client#32
- [x] sopra-fs22-group-23/client#31
- [x] sopra-fs22-group-23/server#54
