### ISSUE TITLE
US14: As an event creator I want to start and end an interactive session, with previously determined tasks, so that every collaborator can see in their browser the task grid.

### ISSUE THREAD

**Issue by bauerDOTuzh** [sopra-fs22-group-23/server#19]
## Acceptance Criteria

- [ ] When the event creator clicks on the button to start the interactive session, every user can access this element with an interactive session in their browser
- [ ] When the event creator ends the session, the session windows disappear from the window of another user

## Task List
- [x] sopra-fs22-group-23/client#36
- [x] sopra-fs22-group-23/client#34
- [x] #94
- [x] #95
- [x] #96
- [x] #130
