### ISSUE TITLE
US2:  As a registered user I want to login to my account with my credentials to use the services that are exclusively available to logged-in users.

### ISSUE THREAD

**Issue by bauerDOTuzh** [sopra-fs22-group-23/server#2]
## Acceptance criteria
- [x] After successful login the dashboard
- [x] Upon failure, an error is displayed, and the user is redirected to the register or login screen
- [x] wrong password or wrong username 
- [x] Logged-in users can log out and log back into their registered profile.

## Task List
- [x] sopra-fs22-group-23/client#3
- [x] sopra-fs22-group-23/client#4
- [x] sopra-fs22-group-23/server#30
- [x] sopra-fs22-group-23/server#31
