### ISSUE TITLE
US15: As an event collaborator I want to online assign tasks from bin to myself or to other collaborators so that we can assign the tasks and collaborators know what their tasks will be in this event.

### ISSUE THREAD

**Issue by bauerDOTuzh** [sopra-fs22-group-23/server#20]
## Acceptance Criteria

- [ ] Collaborators can take tasks from the bin and place them in the bin of any other user
- [ ] As soon as I click on the element, the element gets disabled, so that 2 people cannot move the same element at the time
- [ ] As soon as I drop the element, the element appears on screens of other collaborators as assigned to that bin
- [ ] As soon as the element is assigned to a bin and no one moves the element, the element is now available for the next movement
- [ ] This whole process is synced and the collaborators can see the changes in real-time

## Task List
- [x] sopra-fs22-group-23/client#37
- [x] sopra-fs22-group-23/server#62
- [x] sopra-fs22-group-23/client#61
- [x] sopra-fs22-group-23/client#60
