### ISSUE TITLE
US16: As an event creator, after clicking on a “close session”, I want to evaluate the results so that when the event is coming, I can see what everyone’s task is.

### ISSUE THREAD

**Issue by bauerDOTuzh** [sopra-fs22-group-23/server#21]
## Acceptance Criteria

- [ ] After terminating the session, everyone’s bin is saved 
- [x] The assigned tasks are saved for each user so that the event creator has an overview of each user’s tasks without restarting the session

## Task List
- [x] sopra-fs22-group-23/client#55
- [x] sopra-fs22-group-23/server#68
- [x] sopra-fs22-group-23/client#41
- [x] sopra-fs22-group-23/client#40
