### ISSUE TITLE
US19:  As an event collaborator, I want to see live how other collaborators are moving the tasks so that I cannot move them

### ISSUE THREAD

**Issue by bauerDOTuzh** [sopra-fs22-group-23/server#24]
## Acceptance Criteria

- [ ] If the collaborator starts moving the task, the task is not only moving in his window  but the movements are also translated into the browser of other collaborators
- [ ] If one collaborator is moving the task, then the others cannot access the task and move it or “steal” it from the movement
- [ ] As soon as the task is dropped to the new column, any other collaborator can grab it and repeat the same process

## Task List
- [x] sopra-fs22-group-23/client#46
- [x] sopra-fs22-group-23/client#47
