### ISSUE TITLE
US20: As an event collaborator, I want to see the location of the event on a map

### ISSUE THREAD

**Issue by bauerDOTuzh** [sopra-fs22-group-23/server#25]
## Acceptance Criteria

- [ ] On the Event Profile Page, the weather Information should be included
- [ ] The location information for the map should be received through a specific API (e.g. Google Maps or HERE).
- [ ] The specific location should be shown on the map (e.g. Zurich)

## Task List
- [x] sopra-fs22-group-23/client#48
- [x] sopra-fs22-group-23/server#79
- [x] sopra-fs22-group-23/server#80
- [x] sopra-fs22-group-23/client#49
