### ISSUE TITLE
US3: As a registered user, I want to have an overview of all the events that I am invited to or that I am organizing.

### ISSUE THREAD

**Issue by bauerDOTuzh** [sopra-fs22-group-23/server#3]
## Acceptance Criteria

- [x] The page displays all the user’s events. These are sorted in chronological order and divided by the ones that the user is hosting and the ones that they are invited to.
- [x] By clicking on the single event the user can access the event’s information or edit them.
- [x] From the dashboard, the user can access the “create a new event” and “edit your own personal info” functionalities. Moreover, it contains the search bar

## Task List
- [x] sopra-fs22-group-23/client#5
- [x] sopra-fs22-group-23/client#6
- [x] sopra-fs22-group-23/client#7
- [x] sopra-fs22-group-23/client#8
- [x] sopra-fs22-group-23/server#32
- [x] sopra-fs22-group-23/server#33
- [x] sopra-fs22-group-23/server#34
- [x] sopra-fs22-group-23/server#35
