### ISSUE TITLE
US4: As a registered user I want to be able to edit the personal information given in my profile in order to provide an up-to-date impression of myself and control the publication of my personal data.

### ISSUE THREAD

**Issue by bauerDOTuzh** [sopra-fs22-group-23/server#9]
## Acceptance Criteria

- [ ] Edit button in user’s personal overview page
- [ ] Changeable data points are: Username, password
- [ ] Optional data points are: Profile picture, birthdate, biography
- [ ] After changing and saving the data, the user is redirected to his/her overview and the new/changed data is displayed

## Task List
- [x] sopra-fs22-group-23/client#9
- [x] sopra-fs22-group-23/client#10
- [x] sopra-fs22-group-23/server#36
- [x] sopra-fs22-group-23/server#37
- [x] sopra-fs22-group-23/server#144
